name: CI/CD Tienda Perritos - Frontend

on:
  push:
    branches: [ "main" ]
    paths:
      - "frontend/**"

env:
  AWS_REGION: us-east-1
  ECS_CLUSTER: innovatech-cluster-v2
  ECS_SERVICE: innovatech-frontend-service
  ECR_REPOSITORY: innovatech-frontend
  CONTAINER_NAME: frontend-container

jobs:
  build-push-deploy-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Configurar credenciales AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login en Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build imagen Frontend y push a ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: latest
      run: |
        cd frontend
        docker build -t $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG .
        docker push $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG
        echo "image=$ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Desplegar en Amazon ECS Service
      uses: aws-actions/amazon-ecs-deploy-task-definition@v2
      with:
        task-definition: ""
        service: ${{ env.ECS_SERVICE }}
        cluster: ${{ env.ECS_CLUSTER }}
        image: ${{ steps.build-image.outputs.image }}
        
        # Forzar reinicio de pipeline ECS